### PR TITLE
feat: github projects driver added

### PR DESCRIPTION
**Pull request by SanjuEpic**
Hey @FlorentLvr !!
Referring to this issue #235,
Here is the driver code updated

Thanks!

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hello @SanjuEpic ! TY for contribution. 
However, your PR does not pass the PR validation. Could you please check it out ? TY
image

**Comment by SanjuEpic** [comment]
Got it working on it!

**Comment by SanjuEpic** [comment]
This time all validations have passed
Safe to push the driver's code @FlorentLvr!
Thanks!

**Comment by SanjuEpic** [comment]
Sure!

**Pull request merged**
