### PR TITLE
fix: Bug fix in streamlit driver

### LINKED ISSUE #88: Streamlit - Run app with driver
Today, it's possible from Google colab to create an integration with Streamlit (dashboarding/apps) using a "ngrok". 
This could be also integrated in Naas as a driver. 
import naas 
naas.streamlit.add(source="mygraph.html", target="streamlit account")

https://naas.canny.io/requests/p/create-streamlit-driver

### PR DESCRIPTION
**Pull request by gagan3012**
Fixes #88

### CODE REVIEW

**Comment by jravenel** [comment]
Hey @gagan3012 can you provide a bit more details on the fix? I also added @Dr0p42 and @tparente-ui as reviewers + added your task to the roadmap in "In progress" section but we need more details before moving to review.

**Comment by jravenel** [comment]
@gagan3012 validated to try fix

**Comment by jravenel** [comment]
Hello @gagan3012 I have this error when try to launch same example as video.

**Comment by gagan3012** [comment]
Hi I cannot see the screenshot @jravenel

**Comment by jravenel** [comment]
Screenshot 2021-08-17 at 09 37 08
Here it is @gagan3012

**Pull request merged**
