### PR TITLE
fix: streamlit tunnel connection and improve utilisation of driver

### PR DESCRIPTION
**Pull request by tparente-ui**
See the issue : https://github.com/jupyter-naas/drivers/issues/88

Hi ! So, for this issue many things was be changed in the drivers and naas repositories.
As you can see streamlit.py and __init__.py got changes.

- In the streamlit.py, initialisation of a tunnel when the loading Streamlit class will be removed by delete the init part in the Streamlit and BaseApp class
- Rename of the class (NaasStreamlit -> Streamlit)
- Improve utilisation of the function (run.app -> add), added port and path parameters
- Add of the class into __init__.py (so that streamlit is ready for use as soon as the drivers are imported)

Utilisation of the drivers : `naas_drivers.streamlit.add("PATH_OF_FOLDER",port=9999)`

So that the part of the fix in the drivers repo, when we tried to fix the drivers another problem appears, ngrok was missing when we use the drivers and streamlit is not installed (we added a for loop to display errors) see line 37-39.

To continue the fix we've worked on the branch feature/docker-compose on the naas repositorie (this branch is linked to this issue : https://github.com/jupyter-naas/naas/issues/210)

We put the installation of ngrok into the dockerfile, the dockerfile will download the .zip, unzip the folder, take the binary and put him into the folder that streamlit use.

As say before, streamlit was not "installed", in fact that was just because a folder with many other binary drivers was not informed to the environment of naas, so we put a new path to add it into the naas environment.

For test the driver, you need to : 
- Verify that you are in the feature/docker-compose branch on the naas repositorie (https://github.com/jupyter-naas/naas/tree/feature/docker-compose)
- Do a make build
- Do a make
- Wait a few second that the install; of the drivers are finished
- Test the drivers in a notebook like this : 
```
import naas_drivers
naas_drivers.streamlit.add("PATH_OF_FOLDER",port=9999)
```

### CODE REVIEW

**Comment by jravenel** [comment]
Hello @tparente-ui thanks for your work 👍 

Unfortunately, I was able to switch but not able to build.

Screenshot 2021-08-24 at 20 03 02

What are the command lines to do please? "Make build" "Make run"

Thanks

**Comment by tparente-ui** [comment]
Hello @jravenel,

Thanks for your return, you have to do this line : 
- `make build` (to build the docker container)
- `make` (to run the project)

I hope this will help you

**Comment by jravenel** [comment]
Hello, very nice @tparente-ui! My feedback : 

When I launch Streamlit I have the following message : 
‘’’ 
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

Web App can be accessed on: NgrokTunnel: "http://290e-78-202-220-241.ngrok.io" -> "http://localhost:9999"
streamlit run streamlit_app.py --server.port 9999
<subprocess.Popen object at 0x7f9f338cdee0>


‘’’
Is it possible for : 

"http://localhost:9999" : 

→ to be deleted if not working ?

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

→ Should we fix or not tensor and pytorch?
FYI @Dr0p42 @tparente-ui can we analyze where it is used?

**Comment by jravenel** [comment]
Other idea: 

- launch streamlit page automatically 
- if page is closed, then shut down the notebook

Is it possible?

**Pull request merged**
